#! /bin/sh

. ./common/start_functions.sh

if test $# -eq 1; then
    eid=$1
    isEidRunning $eid
else
    eid=`isNodeRunning aRootServer`
    if [ $? -ne 0 ]; then
	exit 1
    fi
fi

hcp tiger_rt_iptables tiger_rt:/
echo "Done cp tiger_rt_iptables to tiger_rt"
himage tiger_rt "/bin/sh ./tiger_rt_iptables"
